# Generated by Django 5.2.4 on 2025-07-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('isPrivate', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('dateUploaded', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('viewCount', models.IntegerField()),
                ('isPrivate', models.BooleanField(default=False)),
                ('videoFile', models.FileField(upload_to='')),
                ('partOfCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='videoplayer.course')),
            ],
        ),
    ]
