# Generated by Django 5.2.4 on 2025-07-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='videoFile',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
