# Generated by Django 5.2.4 on 2025-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0002_alter_lecture_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(default='None', max_length=120),
        ),
    ]
