# Generated by Django 5.2.4 on 2025-07-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0002_alter_lecture_videofile'),
        ('videoplayer', '0002_lecture_thumbnail_alter_lecture_videofile_and_more'),
    ]

    operations = [
    ]
