# Generated by Django 5.2.4 on 2025-07-27 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0003_merge_20250727_1031'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, null=True,related_name='createdCourses', to=settings.AUTH_USER_MODEL),
        ),
    ]
