# Generated by Django 5.2.4 on 2025-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0004_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=None),
        ),
    ]
