# Generated by Django 5.2.4 on 2025-07-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0004_course_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
    ]
