# Generated by Django 5.2.4 on 2025-07-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0005_course_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
