# Generated by Django 5.2.4 on 2025-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0008_alter_course_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stripe_price_id',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
