# Generated by Django 5.2.4 on 2025-07-27 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0008_remove_course_accessibleby_course_accessibleby'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='accessibleBy',
            field=models.ManyToManyField(null=True, related_name='accessibleCourses', to=settings.AUTH_USER_MODEL),
        ),
    ]
