# Generated by Django 5.2.4 on 2025-07-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0003_merge_20250727_1031'),
        ('videoplayer', '0009_alter_course_stripe_price_id'),
    ]

    operations = [
    ]
