# Generated by Django 5.2.4 on 2025-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0009_alter_course_accessibleby'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='transcriptionData',
            field=models.TextField(default=None),
        ),
    ]
