# Generated by Django 5.2.4 on 2025-07-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoplayer', '0010_lecture_transcriptiondata'),
        ('videoplayer', '0010_merge_20250727_1630'),
    ]

    operations = [
    ]
