# Generated by Django 5.2.4 on 2025-07-27 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('videoplayer', '0003_course_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoplayer.course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
